steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - --file=deploy/Dockerfile
      - --tag=${_IMAGE_URI}
      - --build-arg=CI_COMMIT_SHORT_SHA=${_COMMIT}
      - --build-arg=APP_DIR=${_APP_DIR}
      - .
images:
  - ${_IMAGE_URI}
timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_STANDARD_2
substitutions:
  _IMAGE_URI: unset
  _COMMIT: local
  _APP_DIR: shop
